/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as StrategyRouteImport } from './routes/strategy'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as MarketRouteImport } from './routes/market'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FundIdRouteImport } from './routes/fund.$id'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyRoute = StrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FundIdRoute = FundIdRouteImport.update({
  id: '/fund/$id',
  path: '/fund/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/learn': typeof LearnRoute
  '/market': typeof MarketRoute
  '/research': typeof ResearchRoute
  '/strategy': typeof StrategyRoute
  '/tools': typeof ToolsRoute
  '/fund/$id': typeof FundIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/learn': typeof LearnRoute
  '/market': typeof MarketRoute
  '/research': typeof ResearchRoute
  '/strategy': typeof StrategyRoute
  '/tools': typeof ToolsRoute
  '/fund/$id': typeof FundIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/learn': typeof LearnRoute
  '/market': typeof MarketRoute
  '/research': typeof ResearchRoute
  '/strategy': typeof StrategyRoute
  '/tools': typeof ToolsRoute
  '/fund/$id': typeof FundIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analytics'
    | '/compare'
    | '/contact'
    | '/explore'
    | '/learn'
    | '/market'
    | '/research'
    | '/strategy'
    | '/tools'
    | '/fund/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analytics'
    | '/compare'
    | '/contact'
    | '/explore'
    | '/learn'
    | '/market'
    | '/research'
    | '/strategy'
    | '/tools'
    | '/fund/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analytics'
    | '/compare'
    | '/contact'
    | '/explore'
    | '/learn'
    | '/market'
    | '/research'
    | '/strategy'
    | '/tools'
    | '/fund/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  ExploreRoute: typeof ExploreRoute
  LearnRoute: typeof LearnRoute
  MarketRoute: typeof MarketRoute
  ResearchRoute: typeof ResearchRoute
  StrategyRoute: typeof StrategyRoute
  ToolsRoute: typeof ToolsRoute
  FundIdRoute: typeof FundIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy': {
      id: '/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof StrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fund/$id': {
      id: '/fund/$id'
      path: '/fund/$id'
      fullPath: '/fund/$id'
      preLoaderRoute: typeof FundIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalyticsRoute: AnalyticsRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  ExploreRoute: ExploreRoute,
  LearnRoute: LearnRoute,
  MarketRoute: MarketRoute,
  ResearchRoute: ResearchRoute,
  StrategyRoute: StrategyRoute,
  ToolsRoute: ToolsRoute,
  FundIdRoute: FundIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
