export type UpcomingScheme = {
  id: string;
  name: string;
  amc: string;
  strategy: string;
  assetClass: "Equity" | "Hybrid" | "Debt";
  benchmark: string;
  expectedExpense: number; // %
  minInvestment: number; // ₹
  nfoOpen: string; // ISO date
  nfoClose: string; // ISO date
  launchDate: string; // ISO date
  highlights: string[];
  prospectusUrl?: string;
};

// Dates anchored ahead of "today" (May 25, 2026) so the timeline always feels live.
// Swap with DB data later — same shape.
export const UPCOMING: UpcomingScheme[] = [
  {
    id: "axis-long-short-pro",
    name: "Axis Long-Short Pro SIF",
    amc: "Axis Asset Management",
    strategy: "Long-Short",
    assetClass: "Equity",
    benchmark: "NIFTY 500 TRI",
    expectedExpense: 2.25,
    minInvestment: 1000000,
    nfoOpen: "2026-06-02",
    nfoClose: "2026-06-16",
    launchDate: "2026-06-20",
    highlights: ["130/30 structure", "Quant-overlay risk model", "Daily liquidity"],
  },
  {
    id: "kotak-multi-asset-sif",
    name: "Kotak Multi-Asset Opportunities SIF",
    amc: "Kotak Mahindra AMC",
    strategy: "Multi-Asset",
    assetClass: "Hybrid",
    benchmark: "CRISIL Hybrid 50+50",
    expectedExpense: 1.95,
    minInvestment: 1000000,
    nfoOpen: "2026-06-09",
    nfoClose: "2026-06-23",
    launchDate: "2026-06-27",
    highlights: ["Gold + REIT sleeve", "Tactical equity tilt", "Monthly rebalance"],
  },
  {
    id: "sbi-event-driven",
    name: "SBI Event-Driven Alpha SIF",
    amc: "SBI Mutual Fund",
    strategy: "Event Driven",
    assetClass: "Equity",
    benchmark: "NIFTY 200 TRI",
    expectedExpense: 2.4,
    minInvestment: 1000000,
    nfoOpen: "2026-06-15",
    nfoClose: "2026-06-29",
    launchDate: "2026-07-03",
    highlights: ["M&A / buyback focus", "Catalyst-led book", "Concentrated 25 names"],
  },
  {
    id: "icici-market-neutral",
    name: "ICICI Prudential Market Neutral SIF",
    amc: "ICICI Prudential AMC",
    strategy: "Market Neutral",
    assetClass: "Hybrid",
    benchmark: "NIFTY 50 Arbitrage",
    expectedExpense: 1.8,
    minInvestment: 1000000,
    nfoOpen: "2026-06-22",
    nfoClose: "2026-07-06",
    launchDate: "2026-07-10",
    highlights: ["Beta-neutral construction", "Pair-trade engine", "Low drawdown target"],
  },
  {
    id: "hdfc-credit-opps",
    name: "HDFC Credit Opportunities SIF",
    amc: "HDFC Asset Management",
    strategy: "Credit Opportunities",
    assetClass: "Debt",
    benchmark: "CRISIL Composite Bond",
    expectedExpense: 1.45,
    minInvestment: 1000000,
    nfoOpen: "2026-07-01",
    nfoClose: "2026-07-15",
    launchDate: "2026-07-20",
    highlights: ["AA/AA- focus", "Structured-credit sleeve", "Avg maturity 3.5y"],
  },
  {
    id: "nippon-quant-edge",
    name: "Nippon India Quant Edge SIF",
    amc: "Nippon India MF",
    strategy: "Quant",
    assetClass: "Equity",
    benchmark: "NIFTY 500 TRI",
    expectedExpense: 2.1,
    minInvestment: 1000000,
    nfoOpen: "2026-07-08",
    nfoClose: "2026-07-22",
    launchDate: "2026-07-25",
    highlights: ["Factor stack: Q/V/M", "Weekly rebalance", "Long-only book"],
  },
  {
    id: "dsp-arbitrage-plus",
    name: "DSP Arbitrage Plus SIF",
    amc: "DSP Asset Managers",
    strategy: "Arbitrage",
    assetClass: "Debt",
    benchmark: "NIFTY 50 Arbitrage",
    expectedExpense: 1.25,
    minInvestment: 1000000,
    nfoOpen: "2026-07-13",
    nfoClose: "2026-07-27",
    launchDate: "2026-08-01",
    highlights: ["Cash-futures spread", "Index calendar spreads", "Tax-efficient"],
  },
  {
    id: "tata-special-sit",
    name: "Tata Special Situations SIF",
    amc: "Tata Asset Management",
    strategy: "Special Situations",
    assetClass: "Equity",
    benchmark: "NIFTY 500 TRI",
    expectedExpense: 2.5,
    minInvestment: 1000000,
    nfoOpen: "2026-07-20",
    nfoClose: "2026-08-03",
    launchDate: "2026-08-07",
    highlights: ["Demerger / spin-off plays", "Stressed-equity ideas", "Catalyst horizon 6-18m"],
  },
  {
    id: "mirae-hybrid-ls",
    name: "Mirae Asset Hybrid Long-Short SIF",
    amc: "Mirae Asset",
    strategy: "Hybrid Long-Short",
    assetClass: "Hybrid",
    benchmark: "CRISIL Hybrid 65+35",
    expectedExpense: 2.15,
    minInvestment: 1000000,
    nfoOpen: "2026-07-27",
    nfoClose: "2026-08-10",
    launchDate: "2026-08-14",
    highlights: ["60% directional / 40% hedged", "Dynamic net exposure", "Vol-targeted"],
  },
  {
    id: "franklin-sector-rotation",
    name: "Franklin India Sector Rotation SIF",
    amc: "Franklin Templeton",
    strategy: "Quant",
    assetClass: "Equity",
    benchmark: "NIFTY 500 TRI",
    expectedExpense: 2.2,
    minInvestment: 1000000,
    nfoOpen: "2026-08-03",
    nfoClose: "2026-08-17",
    launchDate: "2026-08-21",
    highlights: ["Momentum-led sector picks", "Monthly rebalance", "Risk-on/off overlay"],
  },
];
